"""empty message

Revision ID: 44c8174c151a
Revises: 7a33ddd9f8d2
Create Date: 2023-07-27 23:27:30.391987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c8174c151a'
down_revision = 'a81020ba5cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books_in_wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_books_in_wishlist_bookId', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_books_in_wishlist_book_name_fk', type_='foreignkey')
        batch_op.create_foreign_key('fk_books_in_wishlist_bookId_fk', 'book_browse', ['fk_books_in_wishlist_bookId'], ['id'])
        batch_op.drop_column('fk_books_in_wishlist_book_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books_in_wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_books_in_wishlist_book_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_books_in_wishlist_book_name_fk', 'book_details', ['fk_books_in_wishlist_book_name'], ['book_name'])
        batch_op.drop_column('fk_books_in_wishlist_bookId')

    # ### end Alembic commands ###
