"""Updated models

Revision ID: 7a33ddd9f8d2
Revises: d85698f1afc6
Create Date: 2023-07-24 13:55:59.041429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a33ddd9f8d2'
down_revision = 'd85698f1afc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint('uq_fk_wishlist_userid', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_fk_wishlist_userid', ['fk_wishlist_userid'])

    # ### end Alembic commands ###
