"""Added CreditCard model and linked to User model

Revision ID: a81020ba5cfa
Revises: e283c6edfc07
Create Date: 2023-07-25 21:21:29.452019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81020ba5cfa'
down_revision = 'e283c6edfc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    with op.batch_alter_table('book_browse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_browse', schema=None) as batch_op:
        batch_op.drop_column('genre_name')

    op.create_table('user_profile',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('home_address', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###
