"""added publisher to bookbrowse

Revision ID: ac386232c341
Revises: e283c6edfc07
Create Date: 2023-07-25 21:24:33.289975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac386232c341'
down_revision = 'e283c6edfc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_browse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_browse', schema=None) as batch_op:
        batch_op.drop_column('publisher')

    # ### end Alembic commands ###
