"""empty message

Revision ID: b1945b9150d3
Revises: 7a33ddd9f8d2
Create Date: 2023-07-25 13:39:44.039000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1945b9150d3'
down_revision = '7a33ddd9f8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books_in_wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_books_in_wishlist_bookId', sa.Integer(), sa.ForeignKey('book_browse.id', name='fk_books_in_wishlist_bookId_fk'), nullable=True))
        batch_op.drop_constraint('fk_books_in_wishlist_book_name_fk', type_='foreignkey')
        batch_op.drop_column('fk_books_in_wishlist_book_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books_in_wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_books_in_wishlist_book_name', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_books_in_wishlist_book_name_fk', 'book_details', ['fk_books_in_wishlist_book_name'], ['book_name'])
        batch_op.drop_constraint('fk_books_in_wishlist_bookId_fk', type_='foreignkey')
        batch_op.drop_column('fk_books_in_wishlist_bookId')