"""Updated models

Revision ID: d85698f1afc6
Revises: e283c6edfc07
Create Date: 2023-07-24 13:43:25.233838

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd85698f1afc6'
down_revision = 'e283c6edfc07'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_book_browse')
    with op.batch_alter_table('book_browse', schema=None) as batch_op:
        batch_op.drop_column('genre_name')

    with op.batch_alter_table('books_in_wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_books_in_wishlist_wishlistId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fk_books_in_wishlist_book_name', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_books_in_wishlist_book_name_fk', 'book_details', ['fk_books_in_wishlist_book_name'], ['book_name'])
        batch_op.create_foreign_key('fk_books_in_wishlist_wishlistId_fk', 'wishlist', ['fk_books_in_wishlist_wishlistId'], ['id'])
        batch_op.drop_column('wishlistId')
        batch_op.drop_column('BookId')

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_wishlist_userid', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_fk_wishlist_userid', ['fk_wishlist_userid'])
        batch_op.create_foreign_key('fk_wishlist_userid_fk', 'user_profile', ['fk_wishlist_userid'], ['Id'])
        batch_op.drop_column('userId')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_wishlist_userid_fk', type_='foreignkey')
        batch_op.drop_constraint('uq_fk_wishlist_userid', type_='unique')
        batch_op.drop_column('fk_wishlist_userid')

    with op.batch_alter_table('books_in_wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('BookId', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('wishlistId', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_books_in_wishlist_book_name_fk', type_='foreignkey')
        batch_op.drop_constraint('fk_books_in_wishlist_wishlistId_fk', type_='foreignkey')
        batch_op.drop_column('fk_books_in_wishlist_book_name')
        batch_op.drop_column('fk_books_in_wishlist_wishlistId')

    with op.batch_alter_table('book_browse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_name', sa.VARCHAR(length=50), nullable=True))

    op.create_table('_alembic_tmp_book_browse',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('author', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('copies_sold', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

