"""added genre to BookBrowse Table

Revision ID: e283c6edfc07
Revises: e34ecfc6acd0
Create Date: 2023-07-13 19:02:03.836023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e283c6edfc07'
down_revision = 'e34ecfc6acd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_browse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_browse', schema=None) as batch_op:
        batch_op.drop_column('genre_name')

    # ### end Alembic commands ###
