"""Initial migration

Revision ID: e34ecfc6acd0
Revises: 
Create Date: 2023-06-12 16:42:32.916451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34ecfc6acd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books_testing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_detail', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books_testing', schema=None) as batch_op:
        batch_op.drop_column('book_detail')

    # ### end Alembic commands ###
